# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat2.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x63hat2.proto\x12\x04\x63hat\"O\n\x0e\x43hannelRequest\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\'\n\x0c\x63hannel_type\x18\x02 \x01(\x0e\x32\x11.chat.ChannelType\"\"\n\x0f\x43hannelResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x07\n\x05\x45mpty\"L\n\x0b\x43hannelInfo\x12\x14\n\x0c\x63hannel_name\x18\x01 \x01(\t\x12\'\n\x0c\x63hannel_type\x18\x02 \x01(\x0e\x32\x11.chat.ChannelType\"2\n\x0b\x43hannelList\x12#\n\x08\x63hannels\x18\x01 \x03(\x0b\x32\x11.chat.ChannelInfo\"B\n\x0b\x43hatMessage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x14\n\x0c\x63hannel_name\x18\x03 \x01(\t*\'\n\x0b\x43hannelType\x12\n\n\x06SIMPLE\x10\x00\x12\x0c\n\x08MULTIPLE\x10\x01\x32\xeb\x01\n\x0b\x43hatService\x12<\n\rCreateChannel\x12\x14.chat.ChannelRequest\x1a\x15.chat.ChannelResponse\x12<\n\rDeleteChannel\x12\x14.chat.ChannelRequest\x1a\x15.chat.ChannelResponse\x12.\n\x0cListChannels\x12\x0b.chat.Empty\x1a\x11.chat.ChannelList\x12\x30\n\x04\x43hat\x12\x11.chat.ChatMessage\x1a\x11.chat.ChatMessage(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat2_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANNELTYPE']._serialized_start=345
  _globals['_CHANNELTYPE']._serialized_end=384
  _globals['_CHANNELREQUEST']._serialized_start=21
  _globals['_CHANNELREQUEST']._serialized_end=100
  _globals['_CHANNELRESPONSE']._serialized_start=102
  _globals['_CHANNELRESPONSE']._serialized_end=136
  _globals['_EMPTY']._serialized_start=138
  _globals['_EMPTY']._serialized_end=145
  _globals['_CHANNELINFO']._serialized_start=147
  _globals['_CHANNELINFO']._serialized_end=223
  _globals['_CHANNELLIST']._serialized_start=225
  _globals['_CHANNELLIST']._serialized_end=275
  _globals['_CHATMESSAGE']._serialized_start=277
  _globals['_CHATMESSAGE']._serialized_end=343
  _globals['_CHATSERVICE']._serialized_start=387
  _globals['_CHATSERVICE']._serialized_end=622
# @@protoc_insertion_point(module_scope)
